name: Run Playwright Tests (UI + API)

on:
  push:
    branches: [main, failing-tests]
  workflow_dispatch:

jobs:
  api-tests:
    name: API Tests
    runs-on: ubuntu-latest
    env:
      BOOKING_USER: ${{ secrets.BOOKING_USER }}
      BOOKING_PASS: ${{ secrets.BOOKING_PASS }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run API tests
        run: BOOKING_USER=${{ secrets.BOOKING_USER }} BOOKING_PASS=${{ secrets.BOOKING_PASS }} npx playwright test api-tests

      - name: Upload API test results (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: test-results/

  ui-tests:
    name: UI Tests
    runs-on: ubuntu-latest
    env:
      UI_USER: ${{ secrets.UI_USER }}
      UI_PASSWORD: ${{ secrets.UI_PASSWORD }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run UI tests
        run: npm run test:ui

      - name: Upload UI HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-html-report
          path: playwright-report/

      - name: Upload screenshots and videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ui-artifacts
          path: |
            test-results/
            **/*.png
            **/*.webm
